export const data = [
  {
    projectName: "Gaming Site",
    builtWith: "React",
    githubLink: "",
    liveSite: "",
    image: "",
  },
  {
    projectName: "Gaming Site",
    builtWith: "React",
    githubLink: "",
    liveSite: "",
    image: "",
  },
  {
    projectName: "Gaming Site",
    builtWith: "React",
    githubLink: "",
    liveSite: "",
    image: "",
  },
  {
    projectName: "Gaming Site",
    builtWith: "React",
    githubLink: "",
    liveSite: "",
    image: "",
  },
  {
    projectName: "Gaming Site",
    builtWith: "React",
    githubLink: "",
    liveSite: "",
    image: "",
  },
  {
    projectName: "Gaming Site",
    builtWith: "React",
    githubLink: "",
    liveSite: "",
    image: "",
  },
  {
    projectName: "Gaming Site",
    builtWith: "React",
    githubLink: "",
    liveSite: "",
    image: "",
  },
  {
    projectName: "Gaming Site",
    builtWith: "React",
    githubLink: "",
    liveSite: "",
    image: "",
  },
  {
    projectName: "Gaming Site",
    builtWith: "React",
    githubLink: "",
    liveSite: "",
    image: "",
  },
  {
    projectName: "Gaming Site",
    builtWith: "React",
    githubLink: "",
    liveSite: "",
    image: "",
  },
  {
    projectName: "Gaming Site",
    builtWith: "React",
    githubLink: "",
    liveSite: "",
    image: "",
  },
  {
    projectName: "Gaming Site",
    builtWith: "React",
    githubLink: "",
    liveSite: "",
    image: "",
  },
  {
    projectName: "Gaming Site",
    builtWith: "React",
    githubLink: "",
    liveSite: "",
    image: "",
  },
  {
    projectName: "Gaming Site",
    builtWith: "React",
    githubLink: "",
    liveSite: "",
    image: "",
  },
];
